### ISSUE TITLE
Jazzy compilation

### ISSUE THREAD

**Issue by juandpenan** [igonzf/GPSR_planning#1]
Hi, I was trying to compile the robocup in Jazzy ubuntu 24.0 and I encountered an issue with this repo. Its a silly thing actually you just have to modify the gpsr_demo/package.xml and the gpsr_demo/CMakeLists.txt to include ament_index_cpp like [this](https://github.com/juandpenan/GPSR_planning/commit/8a23f934e9d9e6791ff25b557b2f483fadfecd09) 

I havent checked if this works in Humble but I think it should, since it is a small change. If not, maybe we can create a new branch with this change

Thanks in advance!

**Comment by igonzf** [comment]
Hi, thanks for the suggestion! The repo has been updated with the ament_index_cpp dependency and compiles fine in Humble.

Let me know if you find any other issues.
